In [83]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
^C
ERROR: Operation cancelled by user

In [84]:
from datasets import load_dataset

In [85]:
dataset=load_dataset('CShorten/ML-ArXiv-Papers',split='train')

In [86]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [87]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [88]:
import pandas as pd

In [89]:
df=pd.DataFrame(dataset)
df.sample(5)

,Unnamed: 0.1,Unnamed: 0,title,abstract
69384,69384,69384.0,Learning Associative Inference Using Fast Weig...,Humans can quickly associate stimuli to solv...
93483,93483,93483.0,TsmoBN: Generalization for Unseen Clients in F...,Generalizing federated learning (FL) models ...
87232,87232,87232.0,Predicting the 2020 US Presidential Election w...,One major sub-domain in the subject of polli...
52928,52928,52928.0,Exploring Effects of Random Walk Based Minibat...,"In this paper, we have explored the effects ..."
108118,108118,108118.0,Machine Learning based Framework for Robust Pr...,We consider the problem of dynamic pricing o...

In [90]:
df.shape

(117592, 4)

In [91]:
df=df[['title','abstract']]
df.sample(5)

,title,abstract
104245,Back to Reality: Weakly-supervised 3D Object D...,"In this paper, we propose a weakly-supervise..."
59675,Finding Symmetry Breaking Order Parameters wit...,"Curie's principle states that ""when effects ..."
88275,Ensemble Augmentation for Deep Neural Networks...,Time-series data are one of the fundamental ...
104654,Dual Diffusion Implicit Bridges for Image-to-I...,Common image-to-image translation methods re...
48705,Deep Frequent Spatial Temporal Learning for Fa...,Face anti-spoofing is crucial for the securi...

In [92]:
df=df.head(15000)

In [93]:
df.shape

(15000, 2)

In [94]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [95]:
df["paper_text"]=df['title']+" "+df['abstract']

In [96]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [97]:
type(df[["paper_text"]])

pandas.core.frame.DataFrame

In [98]:
print(df['paper_text'].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [99]:
from sentence_transformers import SentenceTransformer

In [212]:
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

In [213]:
print(type(embedding_model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [102]:
# df['paper_text']=df['paper_text'].apply(lambda x:x.replace('\n',''))
df['paper_text']=df['paper_text'].str.replace('\n','',regex=False)

In [103]:
df['paper_text']=df['paper_text'].str.strip()

In [104]:
sample_text=df['paper_text'].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a randomvariable $Y$ as a function of a related random variable $X$ on the basis of ani.i.d. training sample from the joint distribution of $(X,Y)$. Allowablepredictors are drawn from some specified class, and the goal is to approachasymptotically the performance (expected loss) of the best predictor in theclass. We consider the setting in which one has perfect observation of the$X$-part of the sample, while the $Y$-part has to be communicated at somefinite bit rate. The encoding of the $Y$-values is allowed to depend on the$X$-values. Under suitable regularity conditions on the admissible predictors,the underlying family of probability distributions and the loss function, wegive an information-theoretic characterization of achievable predictorperformance in terms of conditional distortion-rate functions. The ideas areillustrated on the example of nonparametric regression in Gaussian noise.'

In [214]:
embedding = embedding_model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [106]:
embedding[:15]

array([-0.12687647, -0.02378245, -0.00790563,  0.02424844,  0.1218068 ,
        0.03128361,  0.0832822 , -0.09455425,  0.03418481, -0.0151784 ,
       -0.02046121,  0.08573572,  0.10659824, -0.01521946, -0.01140681],
      dtype=float32)

In [215]:
sampple_embedding=embedding_model.encode(df['paper_text'].head(5).to_list())

In [216]:
sampple_embedding.shape

(5, 384)

In [109]:
from sklearn.metrics.pairwise import cosine_similarity

In [110]:
similarity=cosine_similarity(sampple_embedding[0].reshape(1,-1),sampple_embedding[0].reshape(1,-1))
print(similarity)

[[1.]]

In [111]:
similarity=cosine_similarity(sampple_embedding[0].reshape(1,-1),sampple_embedding[1].reshape(1,-1))
print(similarity)

[[0.32237816]]

In [112]:
for i in range(1,5):
  sim=cosine_similarity(sampple_embedding[0].reshape(1,-1),sampple_embedding[i].reshape(1,-1))
  print(sim)

[[0.32237816]]
[[0.2818278]]
[[0.2332605]]
[[0.37914312]]

## GEnerating full embedding

In [113]:
# embedding=model.encode(df['paper_text'].to_list(),batch_size=32,show_progress_bar=True)

In [217]:
import os
# /kaggle/input/datasets/errorcode420/imp-file/my_embeddings1.npy
import numpy as np
if os.path.exists("/kaggle/input/datasets/errorcode420/imp-file/my_embeddings1.npy"):

  print("Loading saved embeddings")
  embeddings =np.load ("/kaggle/input/datasets/errorcode420/imp-file/my_embeddings1.npy")
else:



  print("Generating embeddings")
  embeddings = embedding_model.encode( df["paper_text"].tolist(), batch_size=32,show_progress_bar=True)

  np.save("my_embeddings1.npy", embeddings)

  print("Embeddings saved successfully!")

Loading saved embeddings

In [115]:
print(embedding.shape)
print(type(embedding))

(384,)
<class 'numpy.ndarray'>

In [116]:
# import numpy as np
# np.save('my_embeddings1.npy', embedding)

In [117]:
embedding.dtype

dtype('float32')

FAISS-Facebook AI Similarity Search
 - it make a easy structure for easier and optimum search
 - also known as index

In [118]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.1)

In [119]:
import faiss

In [120]:
# faiss.normalize_L2(embedding)

In [121]:
# index=faiss.IndexFlatIP(384)

In [122]:
# index.add(embedding)

In [123]:
# print(index.ntotal)

In [124]:
if os.path.exists ("/kaggle/input/datasets/errorcode420/imp-file/paper_faiss.index"):
  print("Loading existing FAISS index")

  index =faiss.read_index("/kaggle/input/datasets/errorcode420/imp-file/paper_faiss.index")
else:

  print("Creating new FAISS index")
  faiss.normalize_L2(embeddings)
  index = faiss.IndexFlatIP(384)
  index.add(embeddings)
  faiss.write_index(index,"paper_faiss.index")

  print("FAISS index saved successfully!")

Loading existing FAISS index

In [218]:
query="deep learning for medical image analysis"
query_embedding=embedding_model.encode([query])
# query_embedding.reshape(1,-1)
query_embedding.shape

(1, 384)

In [126]:
faiss.normalize_L2(query_embedding)

In [127]:
D,I=index.search(query_embedding,5)
print(D)
print(I)

[[0.66646755 0.6369015  0.6360254  0.6353009  0.62213385]]
[[10466 12691 11873 13730  7818]]

In [128]:
for i in I:

  print(df.iloc[i]['paper_text'])

10466    A Perspective on Deep Imaging   The combinatio...
12691    High-Resolution Breast Cancer Screening with M...
11873    Classification of MRI data using Deep Learning...
13730    Convolutional Neural Networks for Medical Imag...
7818     How much data is needed to train a medical ima...
Name: paper_text, dtype: object

In [129]:
# import numpy as np
# np.save('my_embeddings.npy', embedding)

In [130]:
df.iloc[10466]['paper_text']

'A Perspective on Deep Imaging   The combination of tomographic imaging and deep learning, or machine learningin general, promises to empower not only image analysis but also imagereconstruction. The latter aspect is considered in this perspective articlewith an emphasis on medical imaging to develop a new generation of imagereconstruction theories and techniques. This direction might lead tointelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical andpreclinical applications. To realize the full impact of machine learning onmedical imaging, major challenges must be addressed.'

In [220]:
def search_paper(query,k=5):
  # query="deep learning for medical image analysis"
  query_embedding=embedding_model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

# query_embedding.reshape(1,-1)
  # query_embedding.shape

In [221]:
D,I=search_paper("deep learning for medical image analysis")
print(D)
print(I)

[[0.66646755 0.6369015  0.6360254  0.6353009  0.62213385]]
[[10466 12691 11873 13730  7818]]

In [222]:
def search_paper(query,k=5):
  # query="deep learning for medical image analysis"
  query_embedding=embedding_model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print()
    print("similarity score:-",score)
    print("TITLE:-", df.iloc[idx]['title'])
    print("ABSTRACT:-", df.iloc[idx]['abstract'][:500])

In [224]:
search_paper("deep learning for medical image analysis",10)

similarity score:- 0.66646755
TITLE:- A Perspective on Deep Imaging
ABSTRACT:-   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

similarity score:- 0.6369015
TITLE:- High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
ABSTRACT:-   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

similarity score:- 0.6360254
TITLE:- Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
ABSTRACT:-   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

similarity score:- 0.6353009
TITLE:- Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
ABSTRACT:-   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

similarity score:- 0.62213385
TITLE:- How much data is needed to train a medical image deep learning system to
  achieve necessary high accuracy?
ABSTRACT:-   The use of Convolutional Neural Networks (CNN) in natural image
classification systems has produced very impressive results. Combined with the
inherent nature of medical images that make them ideal for deep-learning,
further application of such systems to medical image classification holds much
promise. However, the usefulness and potential impact of such a system can be
completely negated if it does not reach a target accuracy. In this paper, we
present a study on determining the optimum size

similarity score:- 0.601086
TITLE:- Deep Learning for the Classification of Lung Nodules
ABSTRACT:-   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

similarity score:- 0.59946084
TITLE:- Self-paced Convolutional Neural Network for Computer Aided Detection in
  Medical Imaging Analysis
ABSTRACT:-   Tissue characterization has long been an important component of Computer
Aided Diagnosis (CAD) systems for automatic lesion detection and further
clinical planning. Motivated by the superior performance of deep learning
methods on various computer vision problems, there has been increasing work
applying deep learning to medical image analysis. However, the development of a
robust and reliable deep learning model for computer-aided diagnosis is still
highly challenging due to the combination of

similarity score:- 0.567479
TITLE:- Deep Learning and Its Applications to Machine Health Monitoring: A
  Survey
ABSTRACT:-   Since 2006, deep learning (DL) has become a rapidly growing research
direction, redefining state-of-the-art performances in a wide range of areas
such as object recognition, image segmentation, speech recognition and machine
translation. In modern manufacturing systems, data-driven machine health
monitoring is gaining in popularity due to the widespread deployment of
low-cost sensors and their connection to the Internet. Meanwhile, deep learning
provides useful tools for processing and analyzi

similarity score:- 0.563515
TITLE:- Implementation of deep learning algorithm for automatic detection of
  brain tumors using intraoperative IR-thermal mapping data
ABSTRACT:-   The efficiency of deep machine learning for automatic delineation of tumor
areas has been demonstrated for intraoperative neuronavigation using active
IR-mapping with the use of the cold test. The proposed approach employs a
matrix IR-imager to remotely register the space-time distribution of surface
temperature pattern, which is determined by the dynamics of local cerebral
blood flow. The advantages of this technique are non-invasiveness, zero risks
for the health of patients and medical staf

similarity score:- 0.54038477
TITLE:- Fully Convolutional Architectures for Multi-Class Segmentation in Chest
  Radiographs
ABSTRACT:-   The success of deep convolutional neural networks on image classification and
recognition tasks has led to new applications in very diversified contexts,
including the field of medical imaging. In this paper we investigate and
propose neural network architectures for automated multi-class segmentation of
anatomical organs in chest radiographs, namely for lungs, clavicles and heart.
We address several open challenges including model overfitting, reducing number
of parameters and handling of sev

In [135]:
# search_paper("data set",10)

In [136]:
# search_paper("world position vs camera position",10)

In [137]:
!pip install transformers==4.46.3

Requirement already satisfied: transformers==4.46.3 in /usr/local/lib/python3.12/dist-packages (4.46.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.34.2)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.4.22)

In [138]:
from transformers import pipeline

In [139]:
summarizer=pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

In [140]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [141]:

summary=summarizer(df.iloc[10466]['abstract'],max_length=120,min_length=40)
print(summary[0]['summary_text'])
print(summary)

The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [142]:
def search_summarizer_paper(query,k=5):
  # query="deep learning for medical image analysis"
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print()
    print("similarity score:-",score)
    print("TITLE:-", df.iloc[idx]['title'])
    print("ABSTRACT:-", df.iloc[idx]['abstract'][:500])
    summary=summarizer(df.iloc[idx]['abstract'],max_length=120,min_length=40,do_sample=False)
    print("SUMMARY:-",summary[0]['summary_text'])

In [143]:
# search_summarizer_paper("deep learning for medical image analysis",5)

In [144]:
# search_paper("deep learning for medical image analysis",10)

In [145]:
!pip install keybert==0.8.5

Requirement already satisfied: keybert==0.8.5 in /usr/local/lib/python3.12/dist-packages (0.8.5)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (5.4.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.46.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (2.10.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.4.3)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.34.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert==0.8.5) (0.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.11.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2026.4.22)

In [146]:
from keybert import KeyBERT

In [147]:
kw_model = KeyBERT(model)

In [148]:
type(kw_model)

keybert._model.KeyBERT

In [149]:
df.iloc[10466]['abstract']

'  The combination of tomographic imaging and deep learning, or machine learning\nin general, promises to empower not only image analysis but also image\nreconstruction. The latter aspect is considered in this perspective article\nwith an emphasis on medical imaging to develop a new generation of image\nreconstruction theories and techniques. This direction might lead to\nintelligent utilization of domain knowledge from big data, innovative\napproaches for image reconstruction, and superior performance in clinical and\npreclinical applications. To realize the full impact of machine learning on\nmedical imaging, major challenges must be addressed.\n'

In [150]:
keywords = kw_model.extract_keywords(df.iloc[10466]['abstract'],keyphrase_ngram_range=(1, 3), stop_words='english')
print(keywords)

[('tomographic imaging deep', 0.6704), ('imaging deep learning', 0.6543), ('learning medical imaging', 0.6041), ('imaging deep', 0.5919), ('medical imaging', 0.5281)]

In [151]:
def search_summarizer_key_paper(query,k=5):
  # query="deep learning for medical image analysis"
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("\n")
    print("similarity score:-",score)
    print("TITLE:-", df.iloc[idx]['title'])
    print("ABSTRACT:-", df.iloc[idx]['abstract'][:500])
    summary=summarizer(df.iloc[idx]['abstract'],max_length=120,min_length=40,do_sample=False)
    print("SUMMARY:-",summary[0]['summary_text'])
    print("KEYWORDS:-",end=" ")
    key=kw_model.extract_keywords(df.iloc[idx]['abstract'],keyphrase_ngram_range=(1, 3), stop_words='english')
    for i in key:
      print(i[0],end=',')

In [152]:
# search_summarizer_key_paper("deep learning for medical image analysis",5)

- python on medical dataset with fast api
entity telling it it can tell eg fast api => framework  python-> programing
NER-name entity recognition

RAG pipeline

In [173]:
from datasets import load_dataset,get_dataset_config_names

# dataset = load_dataset("nsusemiehl/SciERC")
# print(get_dataset_config_names("zj/SciERC"))
# from datasets import load_dataset

dataset = load_dataset("zj88zj/SCIERC")

train.json: 0.00B [00:00, ?B/s]

dev.json: 0.00B [00:00, ?B/s]

test.json: 0.00B [00:00, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [174]:
print(dataset)
print(dataset["train"][0])

DatasetDict({
    train: Dataset({
        features: ['clusters', 'sentences', 'ner', 'relations', 'doc_key'],
        num_rows: 350
    })
    validation: Dataset({
        features: ['clusters', 'sentences', 'ner', 'relations', 'doc_key'],
        num_rows: 50
    })
    test: Dataset({
        features: ['clusters', 'sentences', 'ner', 'relations', 'doc_key'],
        num_rows: 100
    })
})
{'clusters': [[[17, 20], [23, 23]]], 'sentences': [['English', 'is', 'shown', 'to', 'be', 'trans-context-free', 'on', 'the', 'basis', 'of', 'coordinations', 'of', 'the', 'respectively', 'type', 'that', 'involve', 'strictly', 'syntactic', 'cross-serial', 'agreement', '.'], ['The', 'agreement', 'in', 'question', 'involves', 'number', 'in', 'nouns', 'and', 'reflexive', 'pronouns', 'and', 'is', 'syntactic', 'rather', 'than', 'semantic', 'in', 'nature', 'because', 'grammatical', 'number', 'in', 'English', ',', 'like', 'grammatical', 'gender', 'in', 'languages', 'such', 'as', 'French', ',', 'is', 'partly', 'arbitrary', '.'], ['The', 'formal', 'proof', ',', 'which', 'makes', 'crucial', 'use', 'of', 'the', 'Interchange', 'Lemma', 'of', 'Ogden', 'et', 'al.', ',', 'is', 'so', 'constructed', 'as', 'to', 'be', 'valid', 'even', 'if', 'English', 'is', 'presumed', 'to', 'contain', 'grammatical', 'sentences', 'in', 'which', 'respectively', 'operates', 'across', 'a', 'pair', 'of', 'coordinate', 'phrases', 'one', 'of', 'whose', 'members', 'has', 'fewer', 'conjuncts', 'than', 'the', 'other', ';', 'it', 'thus', 'goes', 'through', 'whatever', 'the', 'facts', 'may', 'be', 'regarding', 'constructions', 'with', 'unequal', 'numbers', 'of', 'conjuncts', 'in', 'the', 'scope', 'of', 'respectively', ',', 'whereas', 'other', 'arguments', 'have', 'foundered', 'on', 'this', 'problem', '.']], 'ner': [[[0, 0, 'Material'], [10, 10, 'OtherScientificTerm'], [17, 20, 'OtherScientificTerm']], [[23, 23, 'Generic'], [29, 29, 'OtherScientificTerm'], [31, 32, 'OtherScientificTerm'], [42, 43, 'OtherScientificTerm'], [45, 45, 'Material'], [48, 49, 'OtherScientificTerm'], [51, 51, 'Material'], [54, 54, 'Material']], [[70, 71, 'Method'], [86, 86, 'Material']]], 'relations': [[], [[29, 29, 31, 32, 'CONJUNCTION'], [48, 49, 51, 51, 'FEATURE-OF'], [54, 54, 51, 51, 'HYPONYM-OF']], []], 'doc_key': 'J87-1003'}

In [175]:
labels = [
    "Material",
    "Method",
    "Metric",
    "Task",
    "Generic",
    "OtherScientificTerm"
]

In [177]:
label_list = [
    "O",
    "B-Material","I-Material",
    "B-Method","I-Method",
    "B-Metric","I-Metric",
    "B-Task","I-Task",
    "B-Generic","I-Generic",
    "B-OtherScientificTerm",
    "I-OtherScientificTerm"
]

label2id = {
    l: i for i, l in enumerate(label_list)
}

id2label = {
    i: l for i, l in enumerate(label_list)
}

In [178]:
def process_doc(example):

    tokens = []
    tags = []

    offset = 0

    for sent, ents in zip(
        example["sentences"],
        example["ner"]
    ):

        n = len(sent)

        sent_tags = ["O"] * n

        for start, end, label in ents:

            start -= offset
            end -= offset

            if start < 0 or end >= n:
                continue

            sent_tags[start] = f"B-{label}"

            for i in range(start + 1, end + 1):
                sent_tags[i] = f"I-{label}"

        tokens.extend(sent)
        tags.extend(sent_tags)

        offset += n

    return {
        "tokens": tokens,
        "ner_tags":
            [label2id[t] for t in tags]
    }

In [179]:
processed = dataset.map(
    process_doc,
    remove_columns=
        dataset["train"].column_names
)

Map:   0%|          | 0/350 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [180]:
print(processed["train"][0])

{'tokens': ['English', 'is', 'shown', 'to', 'be', 'trans-context-free', 'on', 'the', 'basis', 'of', 'coordinations', 'of', 'the', 'respectively', 'type', 'that', 'involve', 'strictly', 'syntactic', 'cross-serial', 'agreement', '.', 'The', 'agreement', 'in', 'question', 'involves', 'number', 'in', 'nouns', 'and', 'reflexive', 'pronouns', 'and', 'is', 'syntactic', 'rather', 'than', 'semantic', 'in', 'nature', 'because', 'grammatical', 'number', 'in', 'English', ',', 'like', 'grammatical', 'gender', 'in', 'languages', 'such', 'as', 'French', ',', 'is', 'partly', 'arbitrary', '.', 'The', 'formal', 'proof', ',', 'which', 'makes', 'crucial', 'use', 'of', 'the', 'Interchange', 'Lemma', 'of', 'Ogden', 'et', 'al.', ',', 'is', 'so', 'constructed', 'as', 'to', 'be', 'valid', 'even', 'if', 'English', 'is', 'presumed', 'to', 'contain', 'grammatical', 'sentences', 'in', 'which', 'respectively', 'operates', 'across', 'a', 'pair', 'of', 'coordinate', 'phrases', 'one', 'of', 'whose', 'members', 'has', 'fewer', 'conjuncts', 'than', 'the', 'other', ';', 'it', 'thus', 'goes', 'through', 'whatever', 'the', 'facts', 'may', 'be', 'regarding', 'constructions', 'with', 'unequal', 'numbers', 'of', 'conjuncts', 'in', 'the', 'scope', 'of', 'respectively', ',', 'whereas', 'other', 'arguments', 'have', 'foundered', 'on', 'this', 'problem', '.'], 'ner_tags': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 11, 12, 12, 12, 0, 0, 9, 0, 0, 0, 0, 0, 11, 0, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 0, 1, 0, 0, 11, 12, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [181]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "allenai/scibert_scivocab_cased"
)

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [182]:
def tokenize_and_align_labels(
    examples
):

    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    labels = []

    for i, label in enumerate(
        examples["ner_tags"]
    ):

        word_ids = tokenized.word_ids(
            batch_index=i
        )

        previous = None
        label_ids = []

        for word_id in word_ids:

            if word_id is None:
                label_ids.append(-100)

            elif word_id != previous:
                label_ids.append(
                    label[word_id]
                )

            else:
                label_ids.append(-100)

            previous = word_id

        labels.append(label_ids)

    tokenized["labels"] = labels

    return tokenized

In [183]:
tokenized_ds = processed.map(
    tokenize_and_align_labels,
    batched=True
)

Map:   0%|          | 0/350 [00:00<?, ? examples/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [184]:
from transformers import (
    AutoModelForTokenClassification
)

model = (
    AutoModelForTokenClassification
    .from_pretrained(
        "allenai/scibert_scivocab_cased",
        num_labels=len(label_list),
        id2label=id2label,
        label2id=label2id
    )
)

pytorch_model.bin:   0%|          | 0.00/442M [00:00<?, ?B/s]

Some weights of BertForTokenClassification were not initialized from the model checkpoint at allenai/scibert_scivocab_cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

model.safetensors:   0%|          | 0.00/442M [00:00<?, ?B/s]

In [189]:
import os
os.environ["WANDB_DISABLED"] = "true"

training_args = TrainingArguments(
    output_dir="./scientific_ner",
    report_to="none",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
)

In [195]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)

In [196]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

In [197]:
sample = tokenized_ds["train"][0]

print(type(sample["labels"]))
print(type(sample["labels"][0]))
print(sample["labels"][:10])

<class 'list'>
<class 'int'>
[-100, 1, -100, 0, 0, 0, 0, 0, -100, -100]

In [192]:
print(tokenized_ds["train"][0].keys())
print(tokenized_ds["train"][0]["labels"][:20])
print(type(tokenized_ds["train"][0]["labels"][0]))

dict_keys(['tokens', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'])
[-100, 1, -100, 0, 0, 0, 0, 0, -100, -100, -100, -100, 0, 0, 0, 0, 11, -100, 0, 0]
<class 'int'>

In [198]:
print(processed["train"][0])

print(tokenized_ds["train"][0])

print(type(tokenized_ds["train"][0]["labels"][0]))

{'tokens': ['English', 'is', 'shown', 'to', 'be', 'trans-context-free', 'on', 'the', 'basis', 'of', 'coordinations', 'of', 'the', 'respectively', 'type', 'that', 'involve', 'strictly', 'syntactic', 'cross-serial', 'agreement', '.', 'The', 'agreement', 'in', 'question', 'involves', 'number', 'in', 'nouns', 'and', 'reflexive', 'pronouns', 'and', 'is', 'syntactic', 'rather', 'than', 'semantic', 'in', 'nature', 'because', 'grammatical', 'number', 'in', 'English', ',', 'like', 'grammatical', 'gender', 'in', 'languages', 'such', 'as', 'French', ',', 'is', 'partly', 'arbitrary', '.', 'The', 'formal', 'proof', ',', 'which', 'makes', 'crucial', 'use', 'of', 'the', 'Interchange', 'Lemma', 'of', 'Ogden', 'et', 'al.', ',', 'is', 'so', 'constructed', 'as', 'to', 'be', 'valid', 'even', 'if', 'English', 'is', 'presumed', 'to', 'contain', 'grammatical', 'sentences', 'in', 'which', 'respectively', 'operates', 'across', 'a', 'pair', 'of', 'coordinate', 'phrases', 'one', 'of', 'whose', 'members', 'has', 'fewer', 'conjuncts', 'than', 'the', 'other', ';', 'it', 'thus', 'goes', 'through', 'whatever', 'the', 'facts', 'may', 'be', 'regarding', 'constructions', 'with', 'unequal', 'numbers', 'of', 'conjuncts', 'in', 'the', 'scope', 'of', 'respectively', ',', 'whereas', 'other', 'arguments', 'have', 'foundered', 'on', 'this', 'problem', '.'], 'ner_tags': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 11, 12, 12, 12, 0, 0, 9, 0, 0, 0, 0, 0, 11, 0, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 0, 1, 0, 0, 11, 12, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
{'tokens': ['English', 'is', 'shown', 'to', 'be', 'trans-context-free', 'on', 'the', 'basis', 'of', 'coordinations', 'of', 'the', 'respectively', 'type', 'that', 'involve', 'strictly', 'syntactic', 'cross-serial', 'agreement', '.', 'The', 'agreement', 'in', 'question', 'involves', 'number', 'in', 'nouns', 'and', 'reflexive', 'pronouns', 'and', 'is', 'syntactic', 'rather', 'than', 'semantic', 'in', 'nature', 'because', 'grammatical', 'number', 'in', 'English', ',', 'like', 'grammatical', 'gender', 'in', 'languages', 'such', 'as', 'French', ',', 'is', 'partly', 'arbitrary', '.', 'The', 'formal', 'proof', ',', 'which', 'makes', 'crucial', 'use', 'of', 'the', 'Interchange', 'Lemma', 'of', 'Ogden', 'et', 'al.', ',', 'is', 'so', 'constructed', 'as', 'to', 'be', 'valid', 'even', 'if', 'English', 'is', 'presumed', 'to', 'contain', 'grammatical', 'sentences', 'in', 'which', 'respectively', 'operates', 'across', 'a', 'pair', 'of', 'coordinate', 'phrases', 'one', 'of', 'whose', 'members', 'has', 'fewer', 'conjuncts', 'than', 'the', 'other', ';', 'it', 'thus', 'goes', 'through', 'whatever', 'the', 'facts', 'may', 'be', 'regarding', 'constructions', 'with', 'unequal', 'numbers', 'of', 'conjuncts', 'in', 'the', 'scope', 'of', 'respectively', ',', 'whereas', 'other', 'arguments', 'have', 'foundered', 'on', 'this', 'problem', '.'], 'ner_tags': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 11, 12, 12, 12, 0, 0, 9, 0, 0, 0, 0, 0, 11, 0, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 0, 1, 0, 0, 11, 12, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'input_ids': [101, 4670, 2353, 163, 830, 146, 203, 481, 578, 2330, 578, 2295, 201, 111, 2589, 125, 8390, 30111, 125, 111, 1205, 1294, 202, 4050, 9346, 15441, 2158, 578, 10272, 4407, 211, 111, 4407, 124, 2379, 5415, 681, 124, 28857, 136, 13014, 872, 10664, 12546, 136, 163, 15441, 2469, 515, 6513, 124, 3256, 1096, 27165, 681, 124, 4670, 2353, 430, 2069, 27165, 5372, 124, 7483, 581, 193, 5662, 7668, 30115, 430, 163, 10514, 6169, 211, 111, 4212, 3541, 430, 345, 3853, 6142, 649, 125, 111, 23752, 10255, 125, 18120, 2106, 386, 197, 211, 430, 163, 669, 5150, 193, 146, 203, 2248, 1547, 736, 4670, 2353, 163, 20888, 146, 3682, 27165, 10848, 124, 345, 1205, 15327, 2235, 105, 2198, 125, 7412, 19496, 547, 125, 3584, 3242, 441, 7663, 4624, 18855, 30111, 515, 111, 521, 1820, 305, 1803, 10215, 877, 20750, 111, 11819, 579, 203, 4083, 20080, 188, 26006, 3223, 125, 4624, 18855, 30111, 124, 111, 7951, 125, 1205, 430, 2405, 521, 8890, 375, 858, 738, 201, 306, 1210, 211, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [-100, 1, -100, 0, 0, 0, 0, 0, -100, -100, -100, -100, 0, 0, 0, 0, 11, -100, 0, 0, 0, 0, 0, 0, 11, 12, 12, -100, -100, 12, 0, 0, 9, 0, 0, 0, 0, 0, 11, 0, 11, -100, 12, -100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 0, 1, -100, 0, 0, 11, 12, 0, 1, 0, 0, 1, -100, -100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, -100, 0, 0, -100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -100, -100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -100, -100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -100, 0, 0, 0, 0, -100]}
<class 'int'>

In [199]:
trainer.train()

TrainOutput(global_step=220, training_loss=0.4838204123757102, metrics={'train_runtime': 2312.7192, 'train_samples_per_second': 0.757, 'train_steps_per_second': 0.095, 'total_flos': 219848986078644.0, 'train_loss': 0.4838204123757102, 'epoch': 5.0})

In [200]:
trainer.save_model("/kaggle/working/scientific_ner")
tokenizer.save_pretrained(
    "/kaggle/working/scientific_ner"
)

('/kaggle/working/scientific_ner/tokenizer_config.json',
 '/kaggle/working/scientific_ner/special_tokens_map.json',
 '/kaggle/working/scientific_ner/vocab.txt',
 '/kaggle/working/scientific_ner/added_tokens.json',
 '/kaggle/working/scientific_ner/tokenizer.json')

In [201]:
trainer.evaluate()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.38709843158721924,
 'eval_runtime': 17.4252,
 'eval_samples_per_second': 2.869,
 'eval_steps_per_second': 0.402,
 'epoch': 5.0}

In [202]:
sample = processed["validation"][0]

text = " ".join(sample["tokens"])

print(text)

This paper presents an algorithm for computing optical flow , shape , motion , lighting , and albedo from an image sequence of a rigidly-moving Lambertian object under distant illumination . The problem is formulated in a manner that subsumes structure from motion , multi-view stereo , and photo-metric stereo as special cases . The algorithm utilizes both spatial and temporal intensity variation as cues : the former constrains flow and the latter constrains surface orientation ; combining both cues enables dense reconstruction of both textured and texture-less surfaces . The algorithm works by iteratively estimating affine camera parameters , illumination , shape , and albedo in an alternating fashion . Results are demonstrated on videos of hand-held objects moving in front of a fixed light and camera .

In [3]:
from transformers import pipeline

ner = pipeline(
    "ner",
    model="/kaggle/working/scientific_ner",
    tokenizer="/kaggle/working/scientific_ner",
    aggregation_strategy="simple"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [204]:
entities = ner(text)

for e in entities:
    print(
        e["word"],
        e["entity_group"],
        round(e["score"], 3)
    )

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

algorithm Generic 0.928
computing Task 0.497
optical OtherScientificTerm 0.445
flow Task 0.63
shape, Task 0.364
motion OtherScientificTerm 0.354
lighting OtherScientificTerm 0.503
and Task 0.414
albedo OtherScientificTerm 0.542
image sequence Material 0.733
rigidly - moving lambertian object OtherScientificTerm 0.605
distant illumination OtherScientificTerm 0.83
problem Generic 0.882
structure Method 0.376
from Task 0.468
motion Method 0.431
multi - view Method 0.529
stereo Task 0.568
photo - metric Method 0.576
stereo Task 0.541
algorithm Generic 0.94
spatial and temporal intensity variation OtherScientificTerm 0.911
flow OtherScientificTerm 0.86
surface orientation OtherScientificTerm 0.9
dense reconstruction of Task 0.74
textured and texture - less surfaces OtherScientificTerm 0.787
algorithm Generic 0.949
affine camera parameters OtherScientificTerm 0.94
illumination OtherScientificTerm 0.774
shape OtherScientificTerm 0.516
albedo OtherScientificTerm 0.755
of Material 0.568
hand - held objects Material 0.531
fixed OtherScientificTerm 0.531
camera OtherScientificTerm 0.422

In [205]:
import spacy
from spacy import displacy

nlp = spacy.blank("en")
doc = nlp(text)

spans = []

for ent in entities:
    span = doc.char_span(
        ent["start"],
        ent["end"],
        label=ent["entity_group"]
    )

    if span:
        spans.append(span)

doc.ents = spans

In [206]:
displacy.render(
    doc,
    style="ent",
    jupyter=True
)

In [226]:
def search_abstract_NER(query,k=5):
  # query="deep learning for medical image analysis"
  query_embedding=embedding_model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("\n")
    print("similarity score:-",score)
    print("TITLE:-", df.iloc[idx]['title'])
    print("ABSTRACT:-", df.iloc[idx]['abstract'][:500])
    entities = ner(df.iloc[idx]['abstract'])

    # for e in entities:
    #     print(
    #         e["word"],
    #         e["entity_group"],
    #         round(e["score"], 3)
    #     )
    nlp = spacy.blank("en")
    doc = nlp(df.iloc[idx]['abstract'])
    
    spans = []
    
    for ent in entities:
        span = doc.char_span(
            ent["start"],
            ent["end"],
            label=ent["entity_group"]
        )
    
        if span:
            spans.append(span)
    
    doc.ents = spans

    displacy.render(
    doc,
    style="ent",
    jupyter=True)

In [227]:
search_abstract_NER("deep learning for medical image analysis")
# search_paper("deep learning for medical image analysis",10)

similarity score:- 0.66646755
TITLE:- A Perspective on Deep Imaging
ABSTRACT:-   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

similarity score:- 0.6369015
TITLE:- High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
ABSTRACT:-   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

similarity score:- 0.6360254
TITLE:- Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
ABSTRACT:-   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

similarity score:- 0.6353009
TITLE:- Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
ABSTRACT:-   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

similarity score:- 0.62213385
TITLE:- How much data is needed to train a medical image deep learning system to
  achieve necessary high accuracy?
ABSTRACT:-   The use of Convolutional Neural Networks (CNN) in natural image
classification systems has produced very impressive results. Combined with the
inherent nature of medical images that make them ideal for deep-learning,
further application of such systems to medical image classification holds much
promise. However, the usefulness and potential impact of such a system can be
completely negated if it does not reach a target accuracy. In this paper, we
present a study on determining the optimum size

In [228]:
search_abstract_NER("Attention")

similarity score:- 0.5650257
TITLE:- The Attentive Perceptron
ABSTRACT:-   We propose a focus of attention mechanism to speed up the Perceptron
algorithm. Focus of attention speeds up the Perceptron algorithm by lowering
the number of features evaluated throughout training and prediction. Whereas
the traditional Perceptron evaluates all the features of each example, the
Attentive Perceptron evaluates less features for easy to classify examples,
thereby achieving significant speedups and small losses in prediction accuracy.
Focus of attention allows the Attentive Perc

similarity score:- 0.55778956
TITLE:- Can Active Memory Replace Attention?
ABSTRACT:-   Several mechanisms to focus attention of a neural network on selected parts
of its input or memory have been used successfully in deep learning models in
recent years. Attention has improved image classification, image captioning,
speech recognition, generative models, and learning algorithmic tasks, but it
had probably the largest impact on neural machine translation.
  Recently, similar improvements have been obtained using alternative
mechanisms that do not focus on a single part of a memor

similarity score:- 0.5503372
TITLE:- Testing Visual Attention in Dynamic Environments
ABSTRACT:-   We investigate attention as the active pursuit of useful information. This
contrasts with attention as a mechanism for the attenuation of irrelevant
information. We also consider the role of short-term memory, whose use is
critical to any model incapable of simultaneously perceiving all information on
which its output depends. We present several simple synthetic tasks, which
become considerably more interesting when we impose strong constraints on how a
model can interact with its input, and o

similarity score:- 0.5232289
TITLE:- Show, Attend and Tell: Neural Image Caption Generation with Visual
  Attention
ABSTRACT:-   Inspired by recent work in machine translation and object detection, we
introduce an attention based model that automatically learns to describe the
content of images. We describe how we can train this model in a deterministic
manner using standard backpropagation techniques and stochastically by
maximizing a variational lower bound. We also show through visualization how
the model is able to automatically learn to fix its gaze on salient objects
while generating the corresponding words in the

similarity score:- 0.51506007
TITLE:- A Cheap Linear Attention Mechanism with Fast Lookups and Fixed-Size
  Representations
ABSTRACT:-   The softmax content-based attention mechanism has proven to be very
beneficial in many applications of recurrent neural networks. Nevertheless it
suffers from two major computational limitations. First, its computations for
an attention lookup scale linearly in the size of the attended sequence.
Second, it does not encode the sequence into a fixed-size representation but
instead requires to memorize all the hidden states. These two limitations
restrict the use of the softmax attention mechanis

In [5]:
search_abstract_NER("Python")

NameError: name 'search_abstract_NER' is not defined